<template>
  <div class="adapters-page">
    <section class="adapters-hero"><div><span class="hero-kicker">Adapter runtime</span><h2>Adapter 管理</h2><p>安装、启动、停止或重载平台 Adapter。重载会短暂中断对应平台连接。</p></div><div class="hero-actions"><el-button round :loading="loading" @click="loadAdapters">刷新</el-button><el-button round type="primary" @click="installVisible = true">从文件安装</el-button></div></section>
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" />
    <el-alert v-if="message" :title="message" :type="messageType" show-icon closable @close="message = ''" />
    <section class="adapter-layout">
      <aside class="adapter-list"><div class="section-heading"><h3>已安装 Adapter</h3><span>{{ adapters.length }}</span></div><el-skeleton v-if="loading" :rows="4" animated /><el-empty v-else-if="!adapters.length" description="尚未安装 Adapter" /><button v-for="adapter in adapters" :key="adapter.id" class="adapter-row" :class="{ selected: adapter.id === selectedId }" @click="selectedId = adapter.id"><span class="adapter-mark">{{ adapter.platform.slice(0, 1).toUpperCase() }}</span><span><strong>{{ adapter.name }}</strong><small>{{ adapter.id }} · v{{ adapter.version }}</small></span><i :class="adapter.loaded ? 'online' : 'offline'">{{ adapter.loaded ? '运行中' : '已停止' }}</i></button></aside>
      <article class="adapter-detail"><template v-if="selected"><div class="section-heading"><div><span class="hero-kicker">{{ selected.platform }}</span><h3>{{ selected.name }}</h3></div><el-tag :type="selected.loaded ? 'success' : 'info'">{{ selected.loaded ? '运行中' : '已停止' }}</el-tag></div><p v-if="selected.description">{{ selected.description }}</p><dl class="adapter-meta"><div><dt>ID</dt><dd>{{ selected.id }}</dd></div><div><dt>版本</dt><dd>{{ selected.version }}</dd></div><div><dt>程序集</dt><dd>{{ selected.assemblyPath || '—' }}</dd></div></dl><el-alert v-if="selected.error" :title="selected.error" type="error" :closable="false" show-icon /><el-alert v-if="selected.restartRequired" title="此 Adapter 有待完成的更改，需要重启宿主后完全生效。" type="warning" :closable="false" show-icon /><el-alert v-if="selected.rollback" :title="`最近操作回滚状态：${selected.rollback}`" type="warning" :closable="false" show-icon /><div class="action-row"><el-button type="primary" :loading="operation === `${selected.id}:start`" :disabled="Boolean(operation) || selected.loaded" @click="run(selected.id, 'start')">启动</el-button><el-button :loading="operation === `${selected.id}:stop`" :disabled="Boolean(operation) || !selected.loaded" @click="run(selected.id, 'stop')">停止</el-button><el-button :loading="operation === `${selected.id}:reload`" :disabled="Boolean(operation)" @click="run(selected.id, 'reload')">重载</el-button><el-button type="danger" plain :loading="operation === `${selected.id}:delete`" :disabled="Boolean(operation)" @click="run(selected.id, 'delete')">删除</el-button></div></template><el-empty v-else description="从列表选择 Adapter 查看详情" /></article>
    </section>
    <AdapterInstallDialog :visible="installVisible" title="从文件安装 Adapter" :file="installFile" :preview="installPreview" :replace="installReplace" :busy="installBusy" :error="installError" @update:visible="closeInstall" @update:file="installFile = $event" @update:replace="installReplace = $event" @submit="submitInstall" @confirm="confirmInstall" />
  </div>
</template>
<script setup lang="ts">
import AdapterInstallDialog from './components/AdapterInstallDialog.vue'
import { useAdaptersPage } from './Adapters'
const { adapters, selectedId, selected, loading, operation, error, message, messageType, installVisible, installFile, installPreview, installReplace, installError, installBusy, loadAdapters, run, submitInstall, confirmInstall, closeInstall } = useAdaptersPage()
</script>
<style scoped src="./Adapters.css"></style>
